export const options = [
  { value: "Apple", label: "Apple" },
  { value: "Apricots", label: "Apricots" },
  { value: "Avocado", label: "Avocado" },
  { value: "Banana", label: "Banana" },
  { value: "Blackberries", label: "Blackberries" },
  { value: "Blueberries", label: "Blueberries" },
  { value: "Cherries", label: "Cherries" },
  { value: "Cranberries", label: "Cranberries" },
  { value: "Gooseberries", label: "Gooseberries" },
  { value: "Grapefruit", label: "Grapefruit" },
  { value: "Grapes", label: "Grapes" },
  { value: "Guava", label: "Guava" },
  { value: "Kiwifruit", label: "Kiwifruit" },
  { value: "Lychee", label: "Lychee" },
  { value: "Mango", label: "Mango" },
  { value: "Orange", label: "Orange" },
  { value: "Papaya", label: "Papaya" },
  { value: "Peaches", label: "Peaches" },
  { value: "Pineapple", label: "Pineapple" },
  { value: "Pomegranate", label: "Pomegranate" },
  { value: "Raspberries", label: "Raspberries" },
  { value: "Strawberries", label: "Strawberries" },
  { value: "Watermelon", label: "Watermelon" },
];
